//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class employee
    {
        public string name { get; set; }
        public string occupation { get; set; }
        public Nullable<System.DateTime> working_date { get; set; }
        public string working_hours { get; set; }
        public Nullable<int> salary { get; set; }
    }
}
